version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REGISTRY_URI
      - IMAGE_REPO_URI=$IMAGE_REGISTRY_URI/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - |
        docker build -t $IMAGE_REPO_URI:latest \
        --build-arg BASE_PATH=$BASE_PATH \
        .
      - docker tag $IMAGE_REPO_URI:latest $IMAGE_REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $IMAGE_REPO_URI:latest
      - docker push $IMAGE_REPO_URI:$IMAGE_TAG
      - printf '[{"name":"'$CONTAINER_NAME'","imageUri":"'$IMAGE_REPO_URI':'$IMAGE_TAG'"}]' > imagedef.json

artifacts:
  files:
    - imagedef.json
