export const FETCH_LANGUAGE = 'FETCH_LANGUAGE';
export const FETCH_LANGUAGE_FULFILLED = 'FETCH_LANGUAGE_FULFILLED';
export const FETCH_LANGUAGE_REJECTED = 'FETCH_LANGUAGE_REJECTED';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';